name: Video Automation Bot
on:
  schedule:
    - cron: '0 8-23/2 * * *' # Runs daily at 8 AM UTC
  workflow_dispatch: # Allows manual run button

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Run Automation
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: python main.py
